### ISSUE TITLE
It worked，but

### ISSUE THREAD

**Issue by CirillaFionaElenRiannon** [RASBI-CARDNAME/X1_for_mobile_enabler#1]
It was successfully enabled on the Xperia 5 II（android 12）, but I found that even if X1 for Mobile is turned off, it doesn't get disabled. When using VLC player to play 4K videos, it still behaves the same as when it's enabled.
Xperia 5 II（android 12）에서 성공적으로 활성화되었지만, X1 for Mobile이 꺼져도 비활성화되지 않는 것을 발견했습니다. VLC 플레이어로 4K 영상을 재생할 때 활성화 상태와 동일하게 작동합니다.

**Comment by RASBI-CARDNAME** [comment]
First of all, unfortunately, I am not using xperia now : ( 
I think it's a bug in the firmware. There was no problem with the 1 IV model I tested.

And, as you can see from the module structure, this module simply disguises the unlock flag. 

I apologize for the late response. Also, please understand that I'm using a translator.

**Comment by CirillaFionaElenRiannon** [comment]
Thank you for your explanation. Maybe I should reinstall the Xperia firmware. T.T
